/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWhatsNewRouteImport } from './routes/_authenticated/whats-new'
import { Route as AuthenticatedSquadRouteImport } from './routes/_authenticated/squad'
import { Route as AuthenticatedRecordRouteImport } from './routes/_authenticated/record'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDrillsRouteImport } from './routes/_authenticated/drills'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCoachRouteImport } from './routes/_authenticated/coach'
import { Route as AuthenticatedChallengesRouteImport } from './routes/_authenticated/challenges'
import { Route as AuthenticatedChallengeHistoryRouteImport } from './routes/_authenticated/challenge-history'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedSquadIndexRouteImport } from './routes/_authenticated/squad.index'
import { Route as AuthenticatedSessionsIndexRouteImport } from './routes/_authenticated/sessions.index'
import { Route as AuthenticatedCoachIndexRouteImport } from './routes/_authenticated/coach.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedSessionsIdRouteImport } from './routes/_authenticated/sessions.$id'
import { Route as AuthenticatedRecordDrawSlugRouteImport } from './routes/_authenticated/record-draw.$slug'
import { Route as AuthenticatedDrillSlugRouteImport } from './routes/_authenticated/drill.$slug'
import { Route as AuthenticatedChallengeSlugRouteImport } from './routes/_authenticated/challenge.$slug'
import { Route as AuthenticatedChallengeRecordSlugRouteImport } from './routes/_authenticated/challenge-record.$slug'
import { Route as AuthenticatedChallengeProgressSlugRouteImport } from './routes/_authenticated/challenge-progress.$slug'
import { Route as AuthenticatedAdminUserManagementRouteImport } from './routes/_authenticated/admin.user-management'
import { Route as AuthenticatedAdminInvitationsRouteImport } from './routes/_authenticated/admin.invitations'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedCoachPlayersIndexRouteImport } from './routes/_authenticated/coach.players.index'
import { Route as AuthenticatedAdminDevIndexRouteImport } from './routes/_authenticated/admin.dev.index'
import { Route as AuthenticatedSquadVsMemberIdRouteImport } from './routes/_authenticated/squad.vs.$memberId'
import { Route as AuthenticatedSquadLadderSlugRouteImport } from './routes/_authenticated/squad.ladder.$slug'
import { Route as AuthenticatedCoachPlayersPlayerIdRouteImport } from './routes/_authenticated/coach.players.$playerId'
import { Route as AuthenticatedAdminUsersUserIdRouteImport } from './routes/_authenticated/admin.users.$userId'
import { Route as AuthenticatedAdminDevViewUserIdRouteImport } from './routes/_authenticated/admin.dev.view.$userId'
import { Route as AuthenticatedAdminDevUsersUserIdRouteImport } from './routes/_authenticated/admin.dev.users.$userId'
import { Route as AuthenticatedAdminDevSessionsSessionIdRouteImport } from './routes/_authenticated/admin.dev.sessions.$sessionId'
import { Route as AuthenticatedAdminDevResultsResultIdRouteImport } from './routes/_authenticated/admin.dev.results.$resultId'
import { Route as AuthenticatedAdminDevChallengesResultIdRouteImport } from './routes/_authenticated/admin.dev.challenges.$resultId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWhatsNewRoute = AuthenticatedWhatsNewRouteImport.update({
  id: '/whats-new',
  path: '/whats-new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSquadRoute = AuthenticatedSquadRouteImport.update({
  id: '/squad',
  path: '/squad',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecordRoute = AuthenticatedRecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDrillsRoute = AuthenticatedDrillsRouteImport.update({
  id: '/drills',
  path: '/drills',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoachRoute = AuthenticatedCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChallengesRoute = AuthenticatedChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChallengeHistoryRoute =
  AuthenticatedChallengeHistoryRouteImport.update({
    id: '/challenge-history',
    path: '/challenge-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSquadIndexRoute = AuthenticatedSquadIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedSquadRoute,
} as any)
const AuthenticatedSessionsIndexRoute =
  AuthenticatedSessionsIndexRouteImport.update({
    id: '/sessions/',
    path: '/sessions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoachIndexRoute = AuthenticatedCoachIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCoachRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedSessionsIdRoute = AuthenticatedSessionsIdRouteImport.update({
  id: '/sessions/$id',
  path: '/sessions/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecordDrawSlugRoute =
  AuthenticatedRecordDrawSlugRouteImport.update({
    id: '/record-draw/$slug',
    path: '/record-draw/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDrillSlugRoute = AuthenticatedDrillSlugRouteImport.update({
  id: '/drill/$slug',
  path: '/drill/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChallengeSlugRoute =
  AuthenticatedChallengeSlugRouteImport.update({
    id: '/challenge/$slug',
    path: '/challenge/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChallengeRecordSlugRoute =
  AuthenticatedChallengeRecordSlugRouteImport.update({
    id: '/challenge-record/$slug',
    path: '/challenge-record/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChallengeProgressSlugRoute =
  AuthenticatedChallengeProgressSlugRouteImport.update({
    id: '/challenge-progress/$slug',
    path: '/challenge-progress/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUserManagementRoute =
  AuthenticatedAdminUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInvitationsRoute =
  AuthenticatedAdminInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedCoachPlayersIndexRoute =
  AuthenticatedCoachPlayersIndexRouteImport.update({
    id: '/players/',
    path: '/players/',
    getParentRoute: () => AuthenticatedCoachRoute,
  } as any)
const AuthenticatedAdminDevIndexRoute =
  AuthenticatedAdminDevIndexRouteImport.update({
    id: '/dev/',
    path: '/dev/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedSquadVsMemberIdRoute =
  AuthenticatedSquadVsMemberIdRouteImport.update({
    id: '/vs/$memberId',
    path: '/vs/$memberId',
    getParentRoute: () => AuthenticatedSquadRoute,
  } as any)
const AuthenticatedSquadLadderSlugRoute =
  AuthenticatedSquadLadderSlugRouteImport.update({
    id: '/ladder/$slug',
    path: '/ladder/$slug',
    getParentRoute: () => AuthenticatedSquadRoute,
  } as any)
const AuthenticatedCoachPlayersPlayerIdRoute =
  AuthenticatedCoachPlayersPlayerIdRouteImport.update({
    id: '/players/$playerId',
    path: '/players/$playerId',
    getParentRoute: () => AuthenticatedCoachRoute,
  } as any)
const AuthenticatedAdminUsersUserIdRoute =
  AuthenticatedAdminUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDevViewUserIdRoute =
  AuthenticatedAdminDevViewUserIdRouteImport.update({
    id: '/dev/view/$userId',
    path: '/dev/view/$userId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDevUsersUserIdRoute =
  AuthenticatedAdminDevUsersUserIdRouteImport.update({
    id: '/dev/users/$userId',
    path: '/dev/users/$userId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDevSessionsSessionIdRoute =
  AuthenticatedAdminDevSessionsSessionIdRouteImport.update({
    id: '/dev/sessions/$sessionId',
    path: '/dev/sessions/$sessionId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDevResultsResultIdRoute =
  AuthenticatedAdminDevResultsResultIdRouteImport.update({
    id: '/dev/results/$resultId',
    path: '/dev/results/$resultId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDevChallengesResultIdRoute =
  AuthenticatedAdminDevChallengesResultIdRouteImport.update({
    id: '/dev/challenges/$resultId',
    path: '/dev/challenges/$resultId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/challenge-history': typeof AuthenticatedChallengeHistoryRoute
  '/challenges': typeof AuthenticatedChallengesRoute
  '/coach': typeof AuthenticatedCoachRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/drills': typeof AuthenticatedDrillsRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/record': typeof AuthenticatedRecordRoute
  '/squad': typeof AuthenticatedSquadRouteWithChildren
  '/whats-new': typeof AuthenticatedWhatsNewRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/invitations': typeof AuthenticatedAdminInvitationsRoute
  '/admin/user-management': typeof AuthenticatedAdminUserManagementRoute
  '/challenge-progress/$slug': typeof AuthenticatedChallengeProgressSlugRoute
  '/challenge-record/$slug': typeof AuthenticatedChallengeRecordSlugRoute
  '/challenge/$slug': typeof AuthenticatedChallengeSlugRoute
  '/drill/$slug': typeof AuthenticatedDrillSlugRoute
  '/record-draw/$slug': typeof AuthenticatedRecordDrawSlugRoute
  '/sessions/$id': typeof AuthenticatedSessionsIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/coach/': typeof AuthenticatedCoachIndexRoute
  '/sessions/': typeof AuthenticatedSessionsIndexRoute
  '/squad/': typeof AuthenticatedSquadIndexRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/coach/players/$playerId': typeof AuthenticatedCoachPlayersPlayerIdRoute
  '/squad/ladder/$slug': typeof AuthenticatedSquadLadderSlugRoute
  '/squad/vs/$memberId': typeof AuthenticatedSquadVsMemberIdRoute
  '/admin/dev/': typeof AuthenticatedAdminDevIndexRoute
  '/coach/players/': typeof AuthenticatedCoachPlayersIndexRoute
  '/admin/dev/challenges/$resultId': typeof AuthenticatedAdminDevChallengesResultIdRoute
  '/admin/dev/results/$resultId': typeof AuthenticatedAdminDevResultsResultIdRoute
  '/admin/dev/sessions/$sessionId': typeof AuthenticatedAdminDevSessionsSessionIdRoute
  '/admin/dev/users/$userId': typeof AuthenticatedAdminDevUsersUserIdRoute
  '/admin/dev/view/$userId': typeof AuthenticatedAdminDevViewUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/challenge-history': typeof AuthenticatedChallengeHistoryRoute
  '/challenges': typeof AuthenticatedChallengesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/drills': typeof AuthenticatedDrillsRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/record': typeof AuthenticatedRecordRoute
  '/whats-new': typeof AuthenticatedWhatsNewRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/invitations': typeof AuthenticatedAdminInvitationsRoute
  '/admin/user-management': typeof AuthenticatedAdminUserManagementRoute
  '/challenge-progress/$slug': typeof AuthenticatedChallengeProgressSlugRoute
  '/challenge-record/$slug': typeof AuthenticatedChallengeRecordSlugRoute
  '/challenge/$slug': typeof AuthenticatedChallengeSlugRoute
  '/drill/$slug': typeof AuthenticatedDrillSlugRoute
  '/record-draw/$slug': typeof AuthenticatedRecordDrawSlugRoute
  '/sessions/$id': typeof AuthenticatedSessionsIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/coach': typeof AuthenticatedCoachIndexRoute
  '/sessions': typeof AuthenticatedSessionsIndexRoute
  '/squad': typeof AuthenticatedSquadIndexRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/coach/players/$playerId': typeof AuthenticatedCoachPlayersPlayerIdRoute
  '/squad/ladder/$slug': typeof AuthenticatedSquadLadderSlugRoute
  '/squad/vs/$memberId': typeof AuthenticatedSquadVsMemberIdRoute
  '/admin/dev': typeof AuthenticatedAdminDevIndexRoute
  '/coach/players': typeof AuthenticatedCoachPlayersIndexRoute
  '/admin/dev/challenges/$resultId': typeof AuthenticatedAdminDevChallengesResultIdRoute
  '/admin/dev/results/$resultId': typeof AuthenticatedAdminDevResultsResultIdRoute
  '/admin/dev/sessions/$sessionId': typeof AuthenticatedAdminDevSessionsSessionIdRoute
  '/admin/dev/users/$userId': typeof AuthenticatedAdminDevUsersUserIdRoute
  '/admin/dev/view/$userId': typeof AuthenticatedAdminDevViewUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/challenge-history': typeof AuthenticatedChallengeHistoryRoute
  '/_authenticated/challenges': typeof AuthenticatedChallengesRoute
  '/_authenticated/coach': typeof AuthenticatedCoachRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/drills': typeof AuthenticatedDrillsRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/record': typeof AuthenticatedRecordRoute
  '/_authenticated/squad': typeof AuthenticatedSquadRouteWithChildren
  '/_authenticated/whats-new': typeof AuthenticatedWhatsNewRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/invitations': typeof AuthenticatedAdminInvitationsRoute
  '/_authenticated/admin/user-management': typeof AuthenticatedAdminUserManagementRoute
  '/_authenticated/challenge-progress/$slug': typeof AuthenticatedChallengeProgressSlugRoute
  '/_authenticated/challenge-record/$slug': typeof AuthenticatedChallengeRecordSlugRoute
  '/_authenticated/challenge/$slug': typeof AuthenticatedChallengeSlugRoute
  '/_authenticated/drill/$slug': typeof AuthenticatedDrillSlugRoute
  '/_authenticated/record-draw/$slug': typeof AuthenticatedRecordDrawSlugRoute
  '/_authenticated/sessions/$id': typeof AuthenticatedSessionsIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/coach/': typeof AuthenticatedCoachIndexRoute
  '/_authenticated/sessions/': typeof AuthenticatedSessionsIndexRoute
  '/_authenticated/squad/': typeof AuthenticatedSquadIndexRoute
  '/_authenticated/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
  '/_authenticated/coach/players/$playerId': typeof AuthenticatedCoachPlayersPlayerIdRoute
  '/_authenticated/squad/ladder/$slug': typeof AuthenticatedSquadLadderSlugRoute
  '/_authenticated/squad/vs/$memberId': typeof AuthenticatedSquadVsMemberIdRoute
  '/_authenticated/admin/dev/': typeof AuthenticatedAdminDevIndexRoute
  '/_authenticated/coach/players/': typeof AuthenticatedCoachPlayersIndexRoute
  '/_authenticated/admin/dev/challenges/$resultId': typeof AuthenticatedAdminDevChallengesResultIdRoute
  '/_authenticated/admin/dev/results/$resultId': typeof AuthenticatedAdminDevResultsResultIdRoute
  '/_authenticated/admin/dev/sessions/$sessionId': typeof AuthenticatedAdminDevSessionsSessionIdRoute
  '/_authenticated/admin/dev/users/$userId': typeof AuthenticatedAdminDevUsersUserIdRoute
  '/_authenticated/admin/dev/view/$userId': typeof AuthenticatedAdminDevViewUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/challenge-history'
    | '/challenges'
    | '/coach'
    | '/dashboard'
    | '/drills'
    | '/history'
    | '/profile'
    | '/progress'
    | '/record'
    | '/squad'
    | '/whats-new'
    | '/admin/analytics'
    | '/admin/invitations'
    | '/admin/user-management'
    | '/challenge-progress/$slug'
    | '/challenge-record/$slug'
    | '/challenge/$slug'
    | '/drill/$slug'
    | '/record-draw/$slug'
    | '/sessions/$id'
    | '/admin/'
    | '/coach/'
    | '/sessions/'
    | '/squad/'
    | '/admin/users/$userId'
    | '/coach/players/$playerId'
    | '/squad/ladder/$slug'
    | '/squad/vs/$memberId'
    | '/admin/dev/'
    | '/coach/players/'
    | '/admin/dev/challenges/$resultId'
    | '/admin/dev/results/$resultId'
    | '/admin/dev/sessions/$sessionId'
    | '/admin/dev/users/$userId'
    | '/admin/dev/view/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/challenge-history'
    | '/challenges'
    | '/dashboard'
    | '/drills'
    | '/history'
    | '/profile'
    | '/progress'
    | '/record'
    | '/whats-new'
    | '/admin/analytics'
    | '/admin/invitations'
    | '/admin/user-management'
    | '/challenge-progress/$slug'
    | '/challenge-record/$slug'
    | '/challenge/$slug'
    | '/drill/$slug'
    | '/record-draw/$slug'
    | '/sessions/$id'
    | '/admin'
    | '/coach'
    | '/sessions'
    | '/squad'
    | '/admin/users/$userId'
    | '/coach/players/$playerId'
    | '/squad/ladder/$slug'
    | '/squad/vs/$memberId'
    | '/admin/dev'
    | '/coach/players'
    | '/admin/dev/challenges/$resultId'
    | '/admin/dev/results/$resultId'
    | '/admin/dev/sessions/$sessionId'
    | '/admin/dev/users/$userId'
    | '/admin/dev/view/$userId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/challenge-history'
    | '/_authenticated/challenges'
    | '/_authenticated/coach'
    | '/_authenticated/dashboard'
    | '/_authenticated/drills'
    | '/_authenticated/history'
    | '/_authenticated/profile'
    | '/_authenticated/progress'
    | '/_authenticated/record'
    | '/_authenticated/squad'
    | '/_authenticated/whats-new'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/invitations'
    | '/_authenticated/admin/user-management'
    | '/_authenticated/challenge-progress/$slug'
    | '/_authenticated/challenge-record/$slug'
    | '/_authenticated/challenge/$slug'
    | '/_authenticated/drill/$slug'
    | '/_authenticated/record-draw/$slug'
    | '/_authenticated/sessions/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/coach/'
    | '/_authenticated/sessions/'
    | '/_authenticated/squad/'
    | '/_authenticated/admin/users/$userId'
    | '/_authenticated/coach/players/$playerId'
    | '/_authenticated/squad/ladder/$slug'
    | '/_authenticated/squad/vs/$memberId'
    | '/_authenticated/admin/dev/'
    | '/_authenticated/coach/players/'
    | '/_authenticated/admin/dev/challenges/$resultId'
    | '/_authenticated/admin/dev/results/$resultId'
    | '/_authenticated/admin/dev/sessions/$sessionId'
    | '/_authenticated/admin/dev/users/$userId'
    | '/_authenticated/admin/dev/view/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/whats-new': {
      id: '/_authenticated/whats-new'
      path: '/whats-new'
      fullPath: '/whats-new'
      preLoaderRoute: typeof AuthenticatedWhatsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/squad': {
      id: '/_authenticated/squad'
      path: '/squad'
      fullPath: '/squad'
      preLoaderRoute: typeof AuthenticatedSquadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/record': {
      id: '/_authenticated/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof AuthenticatedRecordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drills': {
      id: '/_authenticated/drills'
      path: '/drills'
      fullPath: '/drills'
      preLoaderRoute: typeof AuthenticatedDrillsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coach': {
      id: '/_authenticated/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AuthenticatedCoachRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/challenges': {
      id: '/_authenticated/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof AuthenticatedChallengesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/challenge-history': {
      id: '/_authenticated/challenge-history'
      path: '/challenge-history'
      fullPath: '/challenge-history'
      preLoaderRoute: typeof AuthenticatedChallengeHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/squad/': {
      id: '/_authenticated/squad/'
      path: '/'
      fullPath: '/squad/'
      preLoaderRoute: typeof AuthenticatedSquadIndexRouteImport
      parentRoute: typeof AuthenticatedSquadRoute
    }
    '/_authenticated/sessions/': {
      id: '/_authenticated/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof AuthenticatedSessionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coach/': {
      id: '/_authenticated/coach/'
      path: '/'
      fullPath: '/coach/'
      preLoaderRoute: typeof AuthenticatedCoachIndexRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/sessions/$id': {
      id: '/_authenticated/sessions/$id'
      path: '/sessions/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof AuthenticatedSessionsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/record-draw/$slug': {
      id: '/_authenticated/record-draw/$slug'
      path: '/record-draw/$slug'
      fullPath: '/record-draw/$slug'
      preLoaderRoute: typeof AuthenticatedRecordDrawSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/drill/$slug': {
      id: '/_authenticated/drill/$slug'
      path: '/drill/$slug'
      fullPath: '/drill/$slug'
      preLoaderRoute: typeof AuthenticatedDrillSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/challenge/$slug': {
      id: '/_authenticated/challenge/$slug'
      path: '/challenge/$slug'
      fullPath: '/challenge/$slug'
      preLoaderRoute: typeof AuthenticatedChallengeSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/challenge-record/$slug': {
      id: '/_authenticated/challenge-record/$slug'
      path: '/challenge-record/$slug'
      fullPath: '/challenge-record/$slug'
      preLoaderRoute: typeof AuthenticatedChallengeRecordSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/challenge-progress/$slug': {
      id: '/_authenticated/challenge-progress/$slug'
      path: '/challenge-progress/$slug'
      fullPath: '/challenge-progress/$slug'
      preLoaderRoute: typeof AuthenticatedChallengeProgressSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/user-management': {
      id: '/_authenticated/admin/user-management'
      path: '/user-management'
      fullPath: '/admin/user-management'
      preLoaderRoute: typeof AuthenticatedAdminUserManagementRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/invitations': {
      id: '/_authenticated/admin/invitations'
      path: '/invitations'
      fullPath: '/admin/invitations'
      preLoaderRoute: typeof AuthenticatedAdminInvitationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/coach/players/': {
      id: '/_authenticated/coach/players/'
      path: '/players'
      fullPath: '/coach/players/'
      preLoaderRoute: typeof AuthenticatedCoachPlayersIndexRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/admin/dev/': {
      id: '/_authenticated/admin/dev/'
      path: '/dev'
      fullPath: '/admin/dev/'
      preLoaderRoute: typeof AuthenticatedAdminDevIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/squad/vs/$memberId': {
      id: '/_authenticated/squad/vs/$memberId'
      path: '/vs/$memberId'
      fullPath: '/squad/vs/$memberId'
      preLoaderRoute: typeof AuthenticatedSquadVsMemberIdRouteImport
      parentRoute: typeof AuthenticatedSquadRoute
    }
    '/_authenticated/squad/ladder/$slug': {
      id: '/_authenticated/squad/ladder/$slug'
      path: '/ladder/$slug'
      fullPath: '/squad/ladder/$slug'
      preLoaderRoute: typeof AuthenticatedSquadLadderSlugRouteImport
      parentRoute: typeof AuthenticatedSquadRoute
    }
    '/_authenticated/coach/players/$playerId': {
      id: '/_authenticated/coach/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/coach/players/$playerId'
      preLoaderRoute: typeof AuthenticatedCoachPlayersPlayerIdRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/admin/users/$userId': {
      id: '/_authenticated/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dev/view/$userId': {
      id: '/_authenticated/admin/dev/view/$userId'
      path: '/dev/view/$userId'
      fullPath: '/admin/dev/view/$userId'
      preLoaderRoute: typeof AuthenticatedAdminDevViewUserIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dev/users/$userId': {
      id: '/_authenticated/admin/dev/users/$userId'
      path: '/dev/users/$userId'
      fullPath: '/admin/dev/users/$userId'
      preLoaderRoute: typeof AuthenticatedAdminDevUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dev/sessions/$sessionId': {
      id: '/_authenticated/admin/dev/sessions/$sessionId'
      path: '/dev/sessions/$sessionId'
      fullPath: '/admin/dev/sessions/$sessionId'
      preLoaderRoute: typeof AuthenticatedAdminDevSessionsSessionIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dev/results/$resultId': {
      id: '/_authenticated/admin/dev/results/$resultId'
      path: '/dev/results/$resultId'
      fullPath: '/admin/dev/results/$resultId'
      preLoaderRoute: typeof AuthenticatedAdminDevResultsResultIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dev/challenges/$resultId': {
      id: '/_authenticated/admin/dev/challenges/$resultId'
      path: '/dev/challenges/$resultId'
      fullPath: '/admin/dev/challenges/$resultId'
      preLoaderRoute: typeof AuthenticatedAdminDevChallengesResultIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminInvitationsRoute: typeof AuthenticatedAdminInvitationsRoute
  AuthenticatedAdminUserManagementRoute: typeof AuthenticatedAdminUserManagementRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminUsersUserIdRoute: typeof AuthenticatedAdminUsersUserIdRoute
  AuthenticatedAdminDevIndexRoute: typeof AuthenticatedAdminDevIndexRoute
  AuthenticatedAdminDevChallengesResultIdRoute: typeof AuthenticatedAdminDevChallengesResultIdRoute
  AuthenticatedAdminDevResultsResultIdRoute: typeof AuthenticatedAdminDevResultsResultIdRoute
  AuthenticatedAdminDevSessionsSessionIdRoute: typeof AuthenticatedAdminDevSessionsSessionIdRoute
  AuthenticatedAdminDevUsersUserIdRoute: typeof AuthenticatedAdminDevUsersUserIdRoute
  AuthenticatedAdminDevViewUserIdRoute: typeof AuthenticatedAdminDevViewUserIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminInvitationsRoute: AuthenticatedAdminInvitationsRoute,
  AuthenticatedAdminUserManagementRoute: AuthenticatedAdminUserManagementRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminUsersUserIdRoute: AuthenticatedAdminUsersUserIdRoute,
  AuthenticatedAdminDevIndexRoute: AuthenticatedAdminDevIndexRoute,
  AuthenticatedAdminDevChallengesResultIdRoute:
    AuthenticatedAdminDevChallengesResultIdRoute,
  AuthenticatedAdminDevResultsResultIdRoute:
    AuthenticatedAdminDevResultsResultIdRoute,
  AuthenticatedAdminDevSessionsSessionIdRoute:
    AuthenticatedAdminDevSessionsSessionIdRoute,
  AuthenticatedAdminDevUsersUserIdRoute: AuthenticatedAdminDevUsersUserIdRoute,
  AuthenticatedAdminDevViewUserIdRoute: AuthenticatedAdminDevViewUserIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedCoachRouteChildren {
  AuthenticatedCoachIndexRoute: typeof AuthenticatedCoachIndexRoute
  AuthenticatedCoachPlayersPlayerIdRoute: typeof AuthenticatedCoachPlayersPlayerIdRoute
  AuthenticatedCoachPlayersIndexRoute: typeof AuthenticatedCoachPlayersIndexRoute
}

const AuthenticatedCoachRouteChildren: AuthenticatedCoachRouteChildren = {
  AuthenticatedCoachIndexRoute: AuthenticatedCoachIndexRoute,
  AuthenticatedCoachPlayersPlayerIdRoute:
    AuthenticatedCoachPlayersPlayerIdRoute,
  AuthenticatedCoachPlayersIndexRoute: AuthenticatedCoachPlayersIndexRoute,
}

const AuthenticatedCoachRouteWithChildren =
  AuthenticatedCoachRoute._addFileChildren(AuthenticatedCoachRouteChildren)

interface AuthenticatedSquadRouteChildren {
  AuthenticatedSquadIndexRoute: typeof AuthenticatedSquadIndexRoute
  AuthenticatedSquadLadderSlugRoute: typeof AuthenticatedSquadLadderSlugRoute
  AuthenticatedSquadVsMemberIdRoute: typeof AuthenticatedSquadVsMemberIdRoute
}

const AuthenticatedSquadRouteChildren: AuthenticatedSquadRouteChildren = {
  AuthenticatedSquadIndexRoute: AuthenticatedSquadIndexRoute,
  AuthenticatedSquadLadderSlugRoute: AuthenticatedSquadLadderSlugRoute,
  AuthenticatedSquadVsMemberIdRoute: AuthenticatedSquadVsMemberIdRoute,
}

const AuthenticatedSquadRouteWithChildren =
  AuthenticatedSquadRoute._addFileChildren(AuthenticatedSquadRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedChallengeHistoryRoute: typeof AuthenticatedChallengeHistoryRoute
  AuthenticatedChallengesRoute: typeof AuthenticatedChallengesRoute
  AuthenticatedCoachRoute: typeof AuthenticatedCoachRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDrillsRoute: typeof AuthenticatedDrillsRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedRecordRoute: typeof AuthenticatedRecordRoute
  AuthenticatedSquadRoute: typeof AuthenticatedSquadRouteWithChildren
  AuthenticatedWhatsNewRoute: typeof AuthenticatedWhatsNewRoute
  AuthenticatedChallengeProgressSlugRoute: typeof AuthenticatedChallengeProgressSlugRoute
  AuthenticatedChallengeRecordSlugRoute: typeof AuthenticatedChallengeRecordSlugRoute
  AuthenticatedChallengeSlugRoute: typeof AuthenticatedChallengeSlugRoute
  AuthenticatedDrillSlugRoute: typeof AuthenticatedDrillSlugRoute
  AuthenticatedRecordDrawSlugRoute: typeof AuthenticatedRecordDrawSlugRoute
  AuthenticatedSessionsIdRoute: typeof AuthenticatedSessionsIdRoute
  AuthenticatedSessionsIndexRoute: typeof AuthenticatedSessionsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedChallengeHistoryRoute: AuthenticatedChallengeHistoryRoute,
  AuthenticatedChallengesRoute: AuthenticatedChallengesRoute,
  AuthenticatedCoachRoute: AuthenticatedCoachRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDrillsRoute: AuthenticatedDrillsRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedRecordRoute: AuthenticatedRecordRoute,
  AuthenticatedSquadRoute: AuthenticatedSquadRouteWithChildren,
  AuthenticatedWhatsNewRoute: AuthenticatedWhatsNewRoute,
  AuthenticatedChallengeProgressSlugRoute:
    AuthenticatedChallengeProgressSlugRoute,
  AuthenticatedChallengeRecordSlugRoute: AuthenticatedChallengeRecordSlugRoute,
  AuthenticatedChallengeSlugRoute: AuthenticatedChallengeSlugRoute,
  AuthenticatedDrillSlugRoute: AuthenticatedDrillSlugRoute,
  AuthenticatedRecordDrawSlugRoute: AuthenticatedRecordDrawSlugRoute,
  AuthenticatedSessionsIdRoute: AuthenticatedSessionsIdRoute,
  AuthenticatedSessionsIndexRoute: AuthenticatedSessionsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
